// export const SIGNUP = "SIGNUP";
export const types = {
 USER_SIGNUP_REQUEST:"USER_SIGNUP_REQUEST",
 USER_SIGNUP_SUCCESS:"USER_SIGNUP_SUCCESS",
 USER_SIGNUP_FAILURE:"USER_SIGNUP_FAILURE",

 USER_LOGIN_REQUEST:"USER_LOGIN_REQUEST",
 USER_LOGIN_SUCCESS:"USER_LOGIN_SUCCESS",
 USER_LOGIN_FAILURE:"USER_LOGIN_FAILURE",

 CREATE_FOLDER_REQUEST:"CREATE_FOLDER_REQUEST",
 CREATE_FOLDER_SUCCESS:"CREATE_FOLDER_SUCCESS",
 CREATE_FOLDER_FAILURE:"CREATE_FOLDER_FAILURE",

 GET_FOLDERS_REQUEST:"GET_FOLDERS_REQUEST",
 GET_FOLDERS_SUCCESS:"GET_FOLDERS_SUCCESS",
 GET_FOLDERS_FAILURE:"GET_FOLDERS_FAILURE",

 RENAME_FOLDERS_REQUEST:"RENAME_FOLDERS_REQUEST",
 RENAME_FOLDERS_SUCCESS:"RENAME_FOLDERS_SUCCESS",
 RENAME_FOLDERS_FAILURE:"RENAME_FOLDERS_FAILURE",
}
