// export const SIGNUP = "SIGNUP";
 const actionTypes = {
 USER_SIGNUP_REQUEST:"USER_SIGNUP_REQUEST",
 USER_SIGNUP_SUCCESS:"USER_SIGNUP_SUCCESS",
 USER_SIGNUP_FAILURE:"USER_SIGNUP_FAILURE",

 USER_LOGIN_REQUEST:"USER_LOGIN_REQUEST",
 USER_LOGIN_SUCCESS:"USER_LOGIN_SUCCESS",
 USER_LOGIN_FAILURE:"USER_LOGIN_FAILURE",

 CREATE_FOLDER_REQUEST:"CREATE_FOLDER_REQUEST",
 CREATE_FOLDER_SUCCESS:"CREATE_FOLDER_SUCCESS",
 CREATE_FOLDER_FAILURE:"CREATE_FOLDER_FAILURE",

 GET_FOLDERS_REQUEST:"GET_FOLDERS_REQUEST",
 GET_FOLDERS_SUCCESS:"GET_FOLDERS_SUCCESS",
 GET_FOLDERS_FAILURE:"GET_FOLDERS_FAILURE",

 DELETE_FOLDER_REQUEST:"DELETE_FOLDER_REQUEST",
 DELETE_FOLDER_SUCCESS:"DELETE_FOLDER_SUCCESS",
 DELETE_FOLDER_FAILURE:"DELETE_FOLDER_FAILURE",

 GET_ME_REQUEST:"GET_ME_REQUEST",
 GET_ME_SUCCESS:"GET_ME_SUCCESS",
 GET_ME_FAILURE:"GET_ME_FAILURE",

 RENAME_FOLDERS_REQUEST:"RENAME_FOLDERS_REQUEST",
 RENAME_FOLDERS_SUCCESS:"RENAME_FOLDERS_SUCCESS",
 RENAME_FOLDERS_FAILURE:"RENAME_FOLDERS_FAILURE",

 CREATE_BOOKMARK_REQUEST:"CREATE_BOOKMARK_REQUEST",
 CREATE_BOOKMARK_SUCCESS:"CREATE_BOOKMARK_SUCCESS",
 CREATE_BOOKMARK_FAILURE:"CREATE_BOOKMARK_FAILURE",

 GET_BOOKMARK_REQUEST:"GET_BOOKMARK_REQUEST",
 GET_BOOKMARK_SUCCESS:"GET_BOOKMARK_SUCCESS",
 GET_BOOKMARK_FAILURE:"GET_BOOKMARK_FAILURE",

 DELETE_BOOKMARK_REQUEST:"DELETE_BOOKMARK_REQUEST",
 DELETE_BOOKMARK_SUCCESS:"DELETE_BOOKMARK_SUCCESS",
 DELETE_BOOKMARK_FAILURE:"DELETE_BOOKMARK_FAILURE",

 MOVE_BOOKMARK_REQUEST:"MOVE_BOOKMARK_REQUEST",
 MOVE_BOOKMARK_SUCCESS:"MOVE_BOOKMARK_SUCCESS",
 MOVE_BOOKMARK_FAILURE:"MOVE_BOOKMARK_FAILURE",

 SEARCH_FOLDER_REQUEST:"SEARCH_FOLDER_REQUEST",

 CANCEL_FOLDER_REQUEST:"CANCEL_FOLDER_REQUEST",

 FAV_BOOKMARK_REQUEST:"FAV_BOOKMARK_REQUEST",
 FAV_BOOKMARK_SUCCESS:"FAV_BOOKMARK_SUCCESS",
 FAV_BOOKMARK_FAILURE:"FAV_BOOKMARK_FAILURE",

 ADD_TO_FAVORITE: "ADD_TO_FAVORITE",

 REMOVE_FROM_FAVORITE: "REMOVE_FROM_FAVORITE",

 SHOW_FAVORITES: "SHOW_FAVORITES",

 TOGGLE_VIEW:"TOGGLE_VIEW",
}

export default actionTypes
