// export const SIGNUP = "SIGNUP";
export const types = {
 USER_PROFILE_REQUEST:"USER_PROFILE_REQUEST",
 USER_PROFILE_SUCCESS:"USER_PROFILE_SUCCESS",
 USER_PROFILE_FAILURE:"USER_PROFILE_FAILURE",

 USER_SIGNUP_REQUEST:"USER_SIGNUP_REQUEST",
 USER_SIGNUP_SUCCESS:"USER_SIGNUP_SUCCESS",
 USER_SIGNUP_FAILURE:"USER_SIGNUP_FAILURE",

 USER_LOGIN_REQUEST:"USER_LOGIN_REQUEST",
 USER_LOGIN_SUCCESS:"USER_LOGIN_SUCCESS",
 USER_LOGIN_FAILURE:"USER_LOGIN_FAILURE",
}
